# .render.yaml
services:
  - type: web
    name: crypto-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000
    plan: free
